default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbtuser
      password: dbtpass
      dbname: dbtdb
      schema: public
      port: 5432
      threads: 1